-- 国家信息
INSERT INTO `country`(id,countryname,countrycode) VALUES (1,'Angola','AO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (2,'Afghanistan','AF');
INSERT INTO `country`(id,countryname,countrycode) VALUES (3,'Albania','AL');
INSERT INTO `country`(id,countryname,countrycode) VALUES (4,'Algeria','DZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (5,'Andorra','AD');
INSERT INTO `country`(id,countryname,countrycode) VALUES (6,'Anguilla','AI');
INSERT INTO `country`(id,countryname,countrycode) VALUES (7,'Antigua and Barbuda','AG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (8,'Argentina','AR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (9,'Armenia','AM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (10,'Australia','AU');
INSERT INTO `country`(id,countryname,countrycode) VALUES (11,'Austria','AT');
INSERT INTO `country`(id,countryname,countrycode) VALUES (12,'Azerbaijan','AZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (13,'Bahamas','BS');
INSERT INTO `country`(id,countryname,countrycode) VALUES (14,'Bahrain','BH');
INSERT INTO `country`(id,countryname,countrycode) VALUES (15,'Bangladesh','BD');
INSERT INTO `country`(id,countryname,countrycode) VALUES (16,'Barbados','BB');
INSERT INTO `country`(id,countryname,countrycode) VALUES (17,'Belarus','BY');
INSERT INTO `country`(id,countryname,countrycode) VALUES (18,'Belgium','BE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (19,'Belize','BZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (20,'Benin','BJ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (21,'Bermuda Is.','BM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (22,'Bolivia','BO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (23,'Botswana','BW');
INSERT INTO `country`(id,countryname,countrycode) VALUES (24,'Brazil','BR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (25,'Brunei','BN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (26,'Bulgaria','BG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (27,'Burkina-faso','BF');
INSERT INTO `country`(id,countryname,countrycode) VALUES (28,'Burma','MM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (29,'Burundi','BI');
INSERT INTO `country`(id,countryname,countrycode) VALUES (30,'Cameroon','CM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (31,'Canada','CA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (32,'Central African Republic','CF');
INSERT INTO `country`(id,countryname,countrycode) VALUES (33,'Chad','TD');
INSERT INTO `country`(id,countryname,countrycode) VALUES (34,'Chile','CL');
INSERT INTO `country`(id,countryname,countrycode) VALUES (35,'China','CN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (36,'Colombia','CO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (37,'Congo','CG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (38,'Cook Is.','CK');
INSERT INTO `country`(id,countryname,countrycode) VALUES (39,'Costa Rica','CR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (40,'Cuba','CU');
INSERT INTO `country`(id,countryname,countrycode) VALUES (41,'Cyprus','CY');
INSERT INTO `country`(id,countryname,countrycode) VALUES (42,'Czech Republic','CZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (43,'Denmark','DK');
INSERT INTO `country`(id,countryname,countrycode) VALUES (44,'Djibouti','DJ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (45,'Dominica Rep.','DO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (46,'Ecuador','EC');
INSERT INTO `country`(id,countryname,countrycode) VALUES (47,'Egypt','EG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (48,'EI Salvador','SV');
INSERT INTO `country`(id,countryname,countrycode) VALUES (49,'Estonia','EE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (50,'Ethiopia','ET');
INSERT INTO `country`(id,countryname,countrycode) VALUES (51,'Fiji','FJ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (52,'Finland','FI');
INSERT INTO `country`(id,countryname,countrycode) VALUES (53,'France','FR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (54,'French Guiana','GF');
INSERT INTO `country`(id,countryname,countrycode) VALUES (55,'Gabon','GA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (56,'Gambia','GM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (57,'Georgia','GE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (58,'Germany','DE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (59,'Ghana','GH');
INSERT INTO `country`(id,countryname,countrycode) VALUES (60,'Gibraltar','GI');
INSERT INTO `country`(id,countryname,countrycode) VALUES (61,'Greece','GR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (62,'Grenada','GD');
INSERT INTO `country`(id,countryname,countrycode) VALUES (63,'Guam','GU');
INSERT INTO `country`(id,countryname,countrycode) VALUES (64,'Guatemala','GT');
INSERT INTO `country`(id,countryname,countrycode) VALUES (65,'Guinea','GN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (66,'Guyana','GY');
INSERT INTO `country`(id,countryname,countrycode) VALUES (67,'Haiti','HT');
INSERT INTO `country`(id,countryname,countrycode) VALUES (68,'Honduras','HN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (69,'Hongkong','HK');
INSERT INTO `country`(id,countryname,countrycode) VALUES (70,'Hungary','HU');
INSERT INTO `country`(id,countryname,countrycode) VALUES (71,'Iceland','IS');
INSERT INTO `country`(id,countryname,countrycode) VALUES (72,'India','IN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (73,'Indonesia','ID');
INSERT INTO `country`(id,countryname,countrycode) VALUES (74,'Iran','IR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (75,'Iraq','IQ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (76,'Ireland','IE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (77,'Israel','IL');
INSERT INTO `country`(id,countryname,countrycode) VALUES (78,'Italy','IT');
INSERT INTO `country`(id,countryname,countrycode) VALUES (79,'Jamaica','JM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (80,'Japan','JP');
INSERT INTO `country`(id,countryname,countrycode) VALUES (81,'Jordan','JO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (82,'Kampuchea (Cambodia )','KH');
INSERT INTO `country`(id,countryname,countrycode) VALUES (83,'Kazakstan','KZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (84,'Kenya','KE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (85,'Korea','KR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (86,'Kuwait','KW');
INSERT INTO `country`(id,countryname,countrycode) VALUES (87,'Kyrgyzstan','KG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (88,'Laos','LA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (89,'Latvia','LV');
INSERT INTO `country`(id,countryname,countrycode) VALUES (90,'Lebanon','LB');
INSERT INTO `country`(id,countryname,countrycode) VALUES (91,'Lesotho','LS');
INSERT INTO `country`(id,countryname,countrycode) VALUES (92,'Liberia','LR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (93,'Libya','LY');
INSERT INTO `country`(id,countryname,countrycode) VALUES (94,'Liechtenstein','LI');
INSERT INTO `country`(id,countryname,countrycode) VALUES (95,'Lithuania','LT');
INSERT INTO `country`(id,countryname,countrycode) VALUES (96,'Luxembourg','LU');
INSERT INTO `country`(id,countryname,countrycode) VALUES (97,'Macao','MO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (98,'Madagascar','MG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (99,'Malawi','MW');
INSERT INTO `country`(id,countryname,countrycode) VALUES (100,'Malaysia','MY');
INSERT INTO `country`(id,countryname,countrycode) VALUES (101,'Maldives','MV');
INSERT INTO `country`(id,countryname,countrycode) VALUES (102,'Mali','ML');
INSERT INTO `country`(id,countryname,countrycode) VALUES (103,'Malta','MT');
INSERT INTO `country`(id,countryname,countrycode) VALUES (104,'Mauritius','MU');
INSERT INTO `country`(id,countryname,countrycode) VALUES (105,'Mexico','MX');
INSERT INTO `country`(id,countryname,countrycode) VALUES (106,'Moldova, Republic of','MD');
INSERT INTO `country`(id,countryname,countrycode) VALUES (107,'Monaco','MC');
INSERT INTO `country`(id,countryname,countrycode) VALUES (108,'Mongolia','MN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (109,'Montserrat Is','MS');
INSERT INTO `country`(id,countryname,countrycode) VALUES (110,'Morocco','MA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (111,'Mozambique','MZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (112,'Namibia','NA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (113,'Nauru','NR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (114,'Nepal','NP');
INSERT INTO `country`(id,countryname,countrycode) VALUES (115,'Netherlands','NL');
INSERT INTO `country`(id,countryname,countrycode) VALUES (116,'New Zealand','NZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (117,'Nicaragua','NI');
INSERT INTO `country`(id,countryname,countrycode) VALUES (118,'Niger','NE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (119,'Nigeria','NG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (120,'North Korea','KP');
INSERT INTO `country`(id,countryname,countrycode) VALUES (121,'Norway','NO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (122,'Oman','OM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (123,'Pakistan','PK');
INSERT INTO `country`(id,countryname,countrycode) VALUES (124,'Panama','PA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (125,'Papua New Cuinea','PG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (126,'Paraguay','PY');
INSERT INTO `country`(id,countryname,countrycode) VALUES (127,'Peru','PE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (128,'Philippines','PH');
INSERT INTO `country`(id,countryname,countrycode) VALUES (129,'Poland','PL');
INSERT INTO `country`(id,countryname,countrycode) VALUES (130,'French Polynesia','PF');
INSERT INTO `country`(id,countryname,countrycode) VALUES (131,'Portugal','PT');
INSERT INTO `country`(id,countryname,countrycode) VALUES (132,'Puerto Rico','PR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (133,'Qatar','QA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (134,'Romania','RO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (135,'Russia','RU');
INSERT INTO `country`(id,countryname,countrycode) VALUES (136,'Saint Lueia','LC');
INSERT INTO `country`(id,countryname,countrycode) VALUES (137,'Saint Vincent','VC');
INSERT INTO `country`(id,countryname,countrycode) VALUES (138,'San Marino','SM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (139,'Sao Tome and Principe','ST');
INSERT INTO `country`(id,countryname,countrycode) VALUES (140,'Saudi Arabia','SA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (141,'Senegal','SN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (142,'Seychelles','SC');
INSERT INTO `country`(id,countryname,countrycode) VALUES (143,'Sierra Leone','SL');
INSERT INTO `country`(id,countryname,countrycode) VALUES (144,'Singapore','SG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (145,'Slovakia','SK');
INSERT INTO `country`(id,countryname,countrycode) VALUES (146,'Slovenia','SI');
INSERT INTO `country`(id,countryname,countrycode) VALUES (147,'Solomon Is','SB');
INSERT INTO `country`(id,countryname,countrycode) VALUES (148,'Somali','SO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (149,'South Africa','ZA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (150,'Spain','ES');
INSERT INTO `country`(id,countryname,countrycode) VALUES (151,'Sri Lanka','LK');
INSERT INTO `country`(id,countryname,countrycode) VALUES (152,'St.Lucia','LC');
INSERT INTO `country`(id,countryname,countrycode) VALUES (153,'St.Vincent','VC');
INSERT INTO `country`(id,countryname,countrycode) VALUES (154,'Sudan','SD');
INSERT INTO `country`(id,countryname,countrycode) VALUES (155,'Suriname','SR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (156,'Swaziland','SZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (157,'Sweden','SE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (158,'Switzerland','CH');
INSERT INTO `country`(id,countryname,countrycode) VALUES (159,'Syria','SY');
INSERT INTO `country`(id,countryname,countrycode) VALUES (160,'Taiwan','CN-TW');
INSERT INTO `country`(id,countryname,countrycode) VALUES (161,'Tajikstan','TJ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (162,'Tanzania','TZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (163,'Thailand','TH');
INSERT INTO `country`(id,countryname,countrycode) VALUES (164,'Togo','TG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (165,'Tonga','TO');
INSERT INTO `country`(id,countryname,countrycode) VALUES (166,'Trinidad and Tobago','TT');
INSERT INTO `country`(id,countryname,countrycode) VALUES (167,'Tunisia','TN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (168,'Turkey','TR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (169,'Turkmenistan','TM');
INSERT INTO `country`(id,countryname,countrycode) VALUES (170,'Uganda','UG');
INSERT INTO `country`(id,countryname,countrycode) VALUES (171,'Ukraine','UA');
INSERT INTO `country`(id,countryname,countrycode) VALUES (172,'United Arab Emirates','AE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (173,'United Kiongdom','GB');
INSERT INTO `country`(id,countryname,countrycode) VALUES (174,'United States of America','US');
INSERT INTO `country`(id,countryname,countrycode) VALUES (175,'Uruguay','UY');
INSERT INTO `country`(id,countryname,countrycode) VALUES (176,'Uzbekistan','UZ');
INSERT INTO `country`(id,countryname,countrycode) VALUES (177,'Venezuela','VE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (178,'Vietnam','VN');
INSERT INTO `country`(id,countryname,countrycode) VALUES (179,'Yemen','YE');
INSERT INTO `country`(id,countryname,countrycode) VALUES (180,'Yugoslavia','YU');
INSERT INTO `country`(id,countryname,countrycode) VALUES (181,'Zimbabwe','ZW');
INSERT INTO `country`(id,countryname,countrycode) VALUES (182,'Zaire','ZR');
INSERT INTO `country`(id,countryname,countrycode) VALUES (183,'Zambia','ZM');
